parameters:
    dekalee_cdn77.query.list_resources.class: Dekalee\Cdn77\Query\ListResourcesQuery
    dekalee_cdn77.query.purge_file.class: Dekalee\Cdn77\Query\PurgeFileQuery
    dekalee_cdn77.query.purge_all.class: Dekalee\Cdn77\Query\PurgeAllQuery
    dekalee_cdn77.query.create_resource.class: Dekalee\Cdn77\Query\CreateResourceQuery

services:
    dekalee_cdn77.query.list_resources:
        class: '%dekalee_cdn77.query.list_resources.class%'
        arguments:
            - '%dekalee_cdn77.api.login%'
            - '%dekalee_cdn77.api.password%'
            - '%dekalee_cdn77.url.list%'
            - '@guzzle.client.cdn77'
    dekalee_cdn77.query.purge_file:
        class: '%dekalee_cdn77.query.purge_file.class%'
        arguments:
            - '@dekalee_cdn77.query.list_resources'
            - '%dekalee_cdn77.api.login%'
            - '%dekalee_cdn77.api.password%'
            - '%dekalee_cdn77.url.purge%'
            - '@guzzle.client.cdn77'
    dekalee_cdn77.query.purge_all:
        class: '%dekalee_cdn77.query.purge_all.class%'
        arguments:
            - '@dekalee_cdn77.query.list_resources'
            - '%dekalee_cdn77.api.login%'
            - '%dekalee_cdn77.api.password%'
            - '%dekalee_cdn77.url.purge_all%'
            - '@guzzle.client.cdn77'
    dekalee_cdn77.query.create_resources:
        class: '%dekalee_cdn77.query.create_resource.class%'
        arguments:
            - '%dekalee_cdn77.api.login%'
            - '%dekalee_cdn77.api.password%'
            - '%dekalee_cdn77.url.create%'
            - '@guzzle.client.cdn77'
